version: '3.2'
services:
  trucks:
    build: .
    volumes:
      - ./trucks/:/app/
    depends_on:
      - tb
    command: "/app/start-instances.sh"
  tb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./tb-data:/data
      - ./tb-logs:/var/log/thingsboard
